stages:
# or just have it as a manual cmd?
# use foreach? param sweep discussion https://github.com/iterative/dvc/pull/8187

# maybe delete cache for "production run"
  ontology:
    cmd: python -m mapping.engine infer ../../ontologies/collected/all.ttl -s rdfs -o ontology.ttl
    wdir: work
    deps:
      - ../../ontologies/collected/all.ttl
    outs:
      - ontology.ttl

  map:
    cmd: python -m mapping.speckle --inference=True --validation=True --stream_id=${building}
    wdir: work
    deps:
      - ../s223
      - ../src/mapping
      - ../src/validation
    outs:
      - out.ttl # need to keep tracking this?

  report:
    cmd: quarto render report.qmd
    wdir: work/report
    deps:
      - ../out.ttl
      - report.qmd
    outs:
      - report.html
      - report_files

  # upload:
  #   cmd: python -m graphdb.tasks upload_graph out.ttl --delete=True  --name ${building}
  #   wdir: work
  #   deps:
  #     - out.ttl
# test here? to actually error out if check?
