stages:
# or just have it as a manual cmd?
# use foreach? param sweep discussion https://github.com/iterative/dvc/pull/8187

  map:
    cmd: mapping-run-in  python -m mapping.speckle --semantics=True --stream_id=${building} 
    wdir: work
    deps:
      - ../../ontologies/imported/223p.ttl
      - ../223p
      - ../mapping
    outs:
      - out.ttl

  upload:
    cmd: graphdb-run-in python -m graphdb.tasks upload_graph out.ttl --delete=True  --name ${building}
    wdir: work
    deps:
      - out.ttl
  

# test here? to actually error out if check?
