stages:
# or just have it as a manual cmd?
# use foreach? param sweep discussion https://github.com/iterative/dvc/pull/8187
  #data:
  #  cmd: dvc pull ../input/buildings/${building}.sqlite                       # TODO: make sure it's the same as map-file above
  #  wdir: work/output

#dvc the ontology repo

  ontologies: # https://github.com/iterative/dvc.org/issues/2170 is it possible to have a pipeline with more than one yaml?
    cmd: ontologies-run-in dvc repro
    wdir: ../ontologies

  map:
    cmd: mapping-run-in  python -m mapping.speckle  --stream_id=${building}  # --db-file --map-file --ontology not really params for this new way
    wdir: work/output
    # deps:
    #   - ../../../ontologies/dvc.yaml:make
    outs:
      - out.ttl

  upload_data:
    cmd: mapping-run-in python -m graphdb.tasks upload_graph out.ttl  --name ${building}
    wdir: work/output
    deps:
      - out.ttl

  
  # validate:
  #   cmd: mapping-run-in python pyshacl_err.py --shacl ../../test/${building}.ttl  -f turtle --iterate-rules --advanced -o validation.ttl  inferred.ttl
  #   wdir: work/output
  #   deps:
  #     - inferred.ttl
  #     - ../../test/${building}.ttl
  #   outs:
  #     - validation.ttl



# test here? to actually error out if check?
