

stages:
# use foreach? param sweep discussion https://github.com/iterative/dvc/pull/8187
  map:
    cmd: mapping-run-in inv map --db-file ../input/buildings/${building} --map-file ../input/mappings/${ontology}/${building}/maps.yaml  --ontology ${ontology}
    wdir: work/output
    deps:
      - ../input/buildings/${building}                        # TODO: make sure it's the same as map-file above
      - ../input/mappings/${ontology}/${building}/maps.yaml   # ditto
      - ../../ontologies/${ontology}
    outs:
      - mapped.ttl
      - log


# to_graphdb:
