

stages:
# use foreach? param sweep discussion https://github.com/iterative/dvc/pull/8187
  map:
    cmd: mapping-run-in inv map --db-file ../input/buildings/${building} --map-file ../input/mappings/${ontology}/${building}/maps.yaml  --ontology ${ontology}
    wdir: work/output
    deps:
      - ../input/buildings/${building}
      - ../input/mappings/${ontology}/${building}/maps.yaml
      - ../../ontologies/${ontology}
    outs: # the whole dir or just the ttl file?
      - mapped.ttl
      - log


# to_graphdb:
