stages:
# or just have it as a manual cmd?
# use foreach? param sweep discussion https://github.com/iterative/dvc/pull/8187

  # all:
  #   foreach:
  #     - defs
  #     - all
  #     - applicable
    #do:
  ontology: # need to process ontology a bit more than just collecting files
  # this step is here instead of in 'ontologies' b/c of recursion issues.
  #                                                   param coll name?
    cmd: python -m mapping.engine ontology -i False -d 'ontology' -o ontology.ttl
    wdir: work
    deps:
      #- ../../ontologies/223standard.hash
      - ../../ontologies/.ontoenv # 
    outs:
     - ontology.ttl
  

  map:
    cmd: python -m mapping.speckle --inference=True --validation=True --stream_id=${building}
    wdir: work
    deps:
      - ../s223
      - ontology.ttl
    outs:
      - out.ttl # need to keep tracking this?

  report:
    cmd: quarto render report.qmd
    wdir: work/report
    deps:
      - ../out.ttl
      - report.qmd
    outs:
      - report.html
      - report_files

  # upload:
  #   cmd: python -m graphdb.tasks upload_graph out.ttl --delete=True  --name ${building}
  #   wdir: work
  #   deps:
  #     - out.ttl
# test here? to actually error out if check?
