[project]
name = "speckle"
version = "0.1.0"
description = "Mainly creates a ttl from a speckle json"
authors = [
    {name =  "Majid alDosari", email = "majid.aldosari@pnnl.gov" }, 
]
dependencies = [
    "gql[requests]",
    "urllib3<2",
    #https://github.com/psf/requests/releases/tag/v2.30.0
    "boltons",
    "numpy",]
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipdb",
    "fire", # the cmd only applies in the dev situation
    "rdflib",
    ] 


[tool.hatch.metadata]
allow-direct-references = true


[tool.pytest.ini_options]
addopts = ['-s']
testpaths = ["tests/*.py"]
[tool.pytest-watcher]
now = true
