[project]
name = "speckle"
version = "0.1.0"
description = "Add a short description here"
authors = [
    {name =  "Majid alDosari", email = "majid.aldosari@pnnl.gov" }, 
    { name = "Bilal Faye", email = "bilal.faye@pnnl.gov" }
]
dependencies = [
    "gql[requests]",
    "urllib3<2",
    #https://github.com/psf/requests/releases/tag/v2.30.0
    "jsonpath-ng",
    "requests-cache",
    "rdflib",
]
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["pytest","pytest-watcher", "ipdb",  "syrupy",]

[tool.hatch.metadata]
allow-direct-references = true


[tool.pytest.ini_options]
addopts = ['-s']
testpaths = ["tests/*.py"]
[tool.pytest-watcher]
now = true
