[project]
name = "bim2rdf"
version = "0.1.0"
description = "Convert BIM data to RDF models"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
readme = "README.md"
requires-python = "==3.11.9"
dependencies = [
    "pytqshacl",
    "json2rdf",
    "rdf-engine",
    # 'local' ones
    "rules",
    "mapping",
    #"ontologies",
    "speckle",
]
[project.optional-dependencies]
spklauto = ["specklepy"] # TODO

[dependency-groups]
dev = [
    "pytqshacl[java,cli]",
    "json2rdf[cli]",
    #'aider-install', can uv pip install aider-install
    "ipython", "ipdb", "icecream",
    "project",
    # spklauto
    # pydantic-settings
]

[tool.uv.sources]
# just listing the dirs alphabetically
mapping =        { path = 'mapping'         , editable = true}
project =        { path = 'project'         , editable = true}
rules =          { path = 'rules'           , editable = true}
#ontologies =     { path = 'ontologies'      , editable = true}
speckle =        { path = 'speckle'         , editable = true}
