[project]
name = "semint"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
readme = "README.md"
requires-python = "==3.11.9"
dependencies = [
    # 'local' ones
    "cicd",
    # 'local' ones
    "engine",
    "mapping",
    "models", # borderline dev
    "ontologies",
    "speckle",
    "topquadrant",
    "json2rdf"
]

[dependency-groups]
dev = [
    #'aider-install', can uv pip install aider-install
    "ipython", 
    "ipdb", 
    "icecream",
    "models",
    "mapping",
    "speckle",
    "cicd",
    "project",
    "project_azure",
    "project_dvc",
    "dvcdiff",
    "graphdb",
]

[tool.uv.sources]
# just listing the dirs alphabetically
cicd    =        { path = 'cicd'            , editable = true}
doc    =         { path = 'doc'             , editable = true}
dvcdiff =        { path = 'dvcdiff'         , editable = true}
engine =         { path = 'engine'          , editable = true}
graphdb =        { path = 'graphdb'         , editable = true}
# # infra doesn't have 'code'
mapping =        { path = 'mapping'         , editable = true}
models =         { path = 'models'          , editable = true}
ontologies =     { path = 'ontologies'      , editable = true}
project =        { path = 'project'         , editable = true}
project_azure =  { path = 'project_azure'   , editable = true}
project_dvc =    { path = 'project_dvc'     , editable = true}
speckle =        { path = 'speckle'         , editable = true}
topquadrant =    { path = 'topquadrant'     , editable = true}
viz =            { path = 'viz'             , editable = true}
json2rdf =       { path = 'json2rdf'        , editable = true}
