[project]
name = "semint"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipython", "ipdb",
     "pip" # careful! only for one-offs!
     ]

[tool.hatch.metadata]
allow-direct-references = true

[tool.rye.workspace]
members = [
    "project",
    "project_azure", 
    "project_dvc",
    "doc",
    "ontologies",
    "ontoenv",
    "graphdb",
    "speckle",
    "engine",
    "mapping"
    ]


[tool.rye.scripts]
# per workspace tools are not 'collected'
