[project]
name = "semint"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
dependencies = []
readme = "README.md"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
bypass-selection = true


[tool.rye]
managed = true
dev-dependencies = [
    "ipython", 
    "pip", # careful! only for one-offs!
    # debugging
    "ipdb", 
    "icecream",
    "rich",
     ]

[tool.hatch.metadata]
allow-direct-references = true

[tool.rye.workspace]
members = [
    # dev
    # TODO: want these as "dev" https://github.com/astral-sh/rye/issues/1361
    "project",
    "project_azure", 
    "project_dvc",  "dvcdiff", 
    # /dev
    "doc",
    "ontologies",
    "graphdb",
    "speckle",
    "engine",
    "mapping",
    "topquadrant",
    # products dir
    "models",
   ]


[tool.rye.scripts]
# per workspace tools are not 'collected'
