[project]
name = "semint"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
dependencies = [
    # 'local' ones
    "cicd>=0.1.0",
    # 'local' ones
    "engine",
    "mapping",
    "models", # borderline dev
    "ontologies",
    "speckle",
    "topquadrant",
]
readme = "README.md"
requires-python = "==3.11.9"


[tool.uv]
# dev-deps are not installed transitively
# https://github.com/astral-sh/uv/issues/6935
#https://github.com/astral-sh/uv/issues/7541#issuecomment-2363210945
dev-dependencies = [
    "ipython", 
    #"pip", # careful! only for one-offs! check how uv does this
    # debugging
    "ipdb", 
    "icecream",
    # local. (could just list everything with pkg[dev])
    # ..though uv gives warnings
    "models[dev]",
    "mapping[dev]",
    "speckle[dev]",
    # 'pure',  dev
    "cicd[dev]",
    "project[dev]",
    "project_azure[dev]",
    "project_dvc[dev]",
    "dvcdiff[dev]",
    "graphdb[dev]",
     ]
[tool.uv.sources]
# just listing the dirs alphabetically
cicd    =        { path = 'cicd'            , editable = true}
doc    =         { path = 'doc'             , editable = true}
dvcdiff =        { path = 'dvcdiff'         , editable = true}
engine =         { path = 'engine'          , editable = true}
graphdb =        { path = 'graphdb'         , editable = true}
# # infra doesn't have 'code'
mapping =        { path = 'mapping'         , editable = true}
models =         { path = 'models'          , editable = true}
ontologies =     { path = 'ontologies'      , editable = true}
project =        { path = 'project'         , editable = true}
project_azure =  { path = 'project_azure'   , editable = true}
project_dvc =    { path = 'project_dvc'     , editable = true}
speckle =        { path = 'speckle'         , editable = true}
topquadrant =    { path = 'topquadrant'     , editable = true}
viz =            { path = 'viz'             , editable = true}

[tool.uv.workspace]
# might do 'external'/'release'/'public' ws
# members = [
#     'cicd',
#     'doc',
#     'dvcdiff',
#     'engine',
#     'graphdb',
#     # infra does't have 'code'
#     'mapping',
#     'models',
#     'ontologies',
#     'project',
#     'project_azure',
#     'project_dvc',
#     'speckle',
#     'topquadrant',
#     'viz'
#     ]
