PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meta: <http://meta>

CONSTRUCT {
?lum s223:cnx ?conn.
?conn  a s223:InletConnectionPoint.
?conn rdfs:label "InletConnectionPoint"^^xsd:string.
?conn s223:hasMedium s223:AC-120VLN-1Ph-60Hz. 
}
WHERE {
?lum a s223:Luminaire.
?lum spkl:elementId ?eid.
  {
  ?lumcircuit spkl:Connectors/rdf:rest*/rdf:first ?conn.
  <<?lumcircuit spkl:category  "Lighting Fixtures">> meta: <<?mi spkl:name "electrical/electrical connection">>.
  }
?lumcircuit spkl:elementId ?eid.

}