PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meta: <http://meta>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX qudtqk: <http://qudt.org/vocab/quantitykind/>
PREFIX unit: <http://qudt.org/vocab/unit/>

CONSTRUCT {
?lum s223:cnx ?conn.
?conn  a s223:InletConnectionPoint.
?conn rdfs:label "InletConnectionPoint"^^xsd:string.
?conn s223:hasMedium s223:AC-277VLN-1Ph-60Hz. 
#?conn s223:hasProperty s223:Voltage-277V. 
#?voltage a s223:QuantifiableProperty. 
#?voltage qudt:hasQuantityKind qudt:Voltage.
#?voltage s223:hasValue ?v1. 
#?voltage qudt:hasUnit unit:V.
}
WHERE {
?lum a s223:Luminaire.
?lum spkl:elementId ?eid.
  {
  ?lumcircuit spkl:Connectors ?l.
  ?l  ?in ?r.# list item
  ?r  spkl:referencedId ?conn.
  #?li spkl:connectedConnectorIds ?conn.
  #?lumcircuit spkl:Connectors ?list.
  #list   ?_  ?conn.cd..
  <<?lumcircuit spkl:category  "Lighting Fixtures">> meta: <<?mi spkl:name "electrical/electrical connection">>.
  }
?lumcircuit spkl:elementId ?eid.
#?lumcircuit spkl:parameters/spkl:RBS_ELECTRICAL_DATA/spkl:value ?v1.
}