---
dvc:
    # on mac ...
    #share dir
    dir: dir

git: true # integrations
    #_: true
    #pre-commit: true # not recommended to be false
    #dvc: true
    #commit-msg: true # not recommended to false
