includes:
- '{{root}}/../project/environment.run.yml'
- '{{root}}/../project/environment.run.yml'
- '{{root}}/../project/environment.run.yml'
- '{{root}}/../project/environment.run.yml'
- '{{root}}/../project/environment.run.yml'
- '{{root}}/../project/environment.run.yml'
- '{{root}}/../project/environment.run.yml'
- '{{root}}/../dev-bootstrap/environment.yml'
- '{{root}}/../project/environment.run.yml'
name: estcp-project
