# copy/paste into your workdir and change where appropriate.
{%set project_name=  os.path.basename(os.path.abspath(os.path.join(root, '..')))  %}
name: {{project_name}}-{{os.path.basename(root)}}

{% set keep_here =     not is_included %}  # https://github.com/ESSS/conda-devenv/issues/120
{% set dev_req =       keep_here %}
{% set wrapped_exe =   keep_here %}
{% set run_req =       True %}  # serves as just annotation


# 'internal' dependencies: (sorry it looks ugly but dont know how else w/o a 'real' 'internal_deps' section)
{% set included_workdirs = [] %}
{% if dev_req %}
{{ included_workdirs.append('project') or "" }} # almost needed ("" is just a hack to not output None)
{{ included_workdirs.append('notebooking') or "" }} # optional
{% endif %}
{% if included_workdirs %}
includes:
{% for included in included_workdirs %}
  - '{{root}}/../{{included}}/environment.devenv.yml'
{% endfor %}
{% endif %}


channels:
  - conda-forge
dependencies: []
  # fill out your deps.
  # if no dep is installed conda will not list the created env.
  #- sometestframework         # [dev_req]
  #- some analysis library     # [run_req]

environment:
  # probably want to append to PATH and PYTHONPATH in your env
  # see wrapped exec note in project/environment.devenv.yml
  PATH:
    - '{{root}}'
    # adds all wrapped executables to path.
    # {% for maybe_dir in  os.scandir( os.path.abspath(os.path.join(root, '..')) )   %}
    # {% if maybe_dir.is_dir()  and keep_here %}
    # - {{ os.path.abspath(os.path.join(maybe_dir, "wbin")) }}
    # {% endif %}
    # {% endfor %}
    # adds included workdirs
    {% for workdir in included_workdirs %}
    - {{ os.path.abspath(os.path.join(root, '..', workdir, "wbin")) }}
    {% endfor %}
  
  PYTHONPATH:
    - '{{root}}'
  #                              don't define the following in envs that include this
  WORK_DIR: '{{  os.path.basename(root) }}'                       # [keep_here]
  WORKDIR:  '{{  os.path.basename(root) }}'                       # [keep_here]
  WORK_DIR_PATH: '{{root}}'                                       # [keep_here]
  WORKDIR_PATH:  '{{root}}'                                       # [keep_here]
  PROJECTROOT:  '{{ os.path.abspath(os.path.join(root, '..')) }}' # [keep_here]
  PROJECT_ROOT: '{{ os.path.abspath(os.path.join(root, '..')) }}' # [keep_here]
  PROJECT_NAME: '{{project_name}}'                                # [keep_here]
  STAGE: local-dev  # vs. prod

