dependencies:
  - pyprojroot
  - python=3.7
  - invoke=1.4.1 
  - dvc=1.1.7
  - git 
includes:
- '{{root}}/../dev-bootstrap/environment.yml'
- '{{root}}/../project/environment.run.yml'
name: estcp-project
environment:
  WORK_DIR: project
