#                           add more work if needed
{% set included_workdirs = ['project', ] %}

dependencies: []
environment:
  # probably want to append PATH and PYTHONPATH in your env
  PATH:
    - '{{ os.path.join(root, "wbin") }}'
    - '{{root}}'
  PYTHONPATH:
    - '{{root}}'
  # don't define the following in envs that include this
  WORK_DIR: '{{  os.path.basename(root) }}'                       # [not is_included]
  WORKDIR:  '{{  os.path.basename(root) }}'                       # [not is_included]
  WORK_DIR_PATH: '{{root}}'                                       # [not is_included]
  WORKDIR_PATH:  '{{root}}'                                       # [not is_included]
  PROJECTROOT:  '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
  PROJECT_ROOT: '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
includes:
{% for included in included_workdirs %}
  - '{{root}}/../{{included}}/environment.devenv.yml'
{% endfor %}
name: {{'estcp-' + os.path.basename(root)}}
