dependencies:
  - pyprojroot
  # - python=3.7 # wouldn't be needed goes in devenv
  # - invoke=1.4.1 # move to /bin thing goes in devenv
  # - dvc=1.1.1 # bin thing goes in devenv
  # - git # bin thing
environment:
  PYTHONPATH:
    - '{{root}}/'
  PATH:
    - '{{root}}/wbin'
