{%set project_name=  os.path.basename(os.path.abspath(os.path.join(root, '..')))  %}
# copy/paste into your work dir and fill out where appropriate.
{% set included_workdirs = ['project', ] %}
{% set dev_req =     not is_included %}
{% set run_req =         is_included %}
{% set wrapped_exe = not is_included %}

channels:
  - conda-forge
environment:
  # probably want to append PATH and PYTHONPATH in your env
  PATH:
    - '{{root}}'
    # adds all wrapped executables to path.
    # makes the wrapped exes available in all envs that include project
    # if using a wrapped exe in a work dir, include it as a dependency in include section.
    {% for maybe_dir in  os.scandir( os.path.abspath(os.path.join(root, '..')) )   %}
    {% if maybe_dir.is_dir() %}
    - {{ os.path.abspath(os.path.join(maybe_dir, "wbin")) }}
    {% endif %}
    {% endfor %}
  PYTHONPATH:
    - '{{root}}'
  # don't define the following in envs that include this
  WORK_DIR: '{{  os.path.basename(root) }}'                       # [not is_included]
  WORKDIR:  '{{  os.path.basename(root) }}'                       # [not is_included]
  WORK_DIR_PATH: '{{root}}'                                       # [not is_included]
  WORKDIR_PATH:  '{{root}}'                                       # [not is_included]
  PROJECTROOT:  '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
  PROJECT_ROOT: '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
dependencies:
  - pyprojroot=0.2.0 # minimal package so /something/ gets installed into dependent env
  # otherwise conda will not list the created env :/
  # some of the below tools will be exposed via wrappers in wbin
  # ie, they will not be 'installed' in dependent envs (envs that include this)
  # keep python fixed
  - python=3.7            # [not is_included]
  # code mgt
  - gitpython=3.1         # [not is_included]
  - git                   # [wrapped_exe]
  - pre-commit=2.7        # [wrapped_exe]
  # data/non-source file mgt.
  - dvc=1.8               # [wrapped_exe]
  # env mgt.
  - deps=1.1.1            # [wrapped_exe]
  - exec-wrappers=1.1.4   # [not is_included]
  # automation
  - invoke=1.4.1          # [not is_included]
includes:
  {% for included in included_workdirs %}
    - '{{root}}/../{{included}}/environment.devenv.yml'
  {% endfor %}
name: '{{project_name}}-{{os.path.basename(root)}}'
