dependencies:
  - pyprojroot
  - python=3.7
  - invoke=1.4.1
  - dvc=1.1.7
  - git
  - exec-wrappers=1.1.4
includes:
- '{{root}}/../project/environment.run.yml'
name: estcp-project
environment:
  WORK_DIR: project
