dependencies:
  - pyprojroot
  - python=3.7
  - invoke=1.4.1
  - dvc=1.4.0
  - git
  - gitpython=3.1.3
  - exec-wrappers=1.1.4
  - pre-commit=2.6.0
includes:
- '{{root}}/../project/environment.run.yml'
name: estcp-project
environment:
  WORK_DIR: project
