channels:
  - conda-forge
dependencies:
  - pyprojroot # minimal package so /something/ gets installed into dependent env
  # otherwise conda will not list the created env :/
  # some of the below tools will be exposed via wrappers in wbin
  - python=3.7            # [not is_included]
  - invoke=1.4.1          # [not is_included]
  - dvc=1.4.0             # [not is_included]
  - git                   # [not is_included]
  - gitpython=3.1.3       # [not is_included]
  - exec-wrappers=1.1.4   # [not is_included]
  - pre-commit=2.6.0      # [not is_included]
environment:
  PATH:
  - '{{root}}/wbin'
  - '{{root}}'
  PYTHONPATH:
  - '{{root}}'
name: estcp-project
