channels:
  - conda-forge
dependencies:
  - pyprojroot # useful but also actcs as a (minimal) stub so that /something/ gets put into an env
  # pip local install ?
  # or conda build??
  # or just have something called setup and build .simplescript
  # or setup.bat/sh in proj root?
environment:
  PYTHONPATH:
    - '{{root}}'
  PATH:
    - '{{root}}/wbin'
  RUN_WORK_DIRS:
    - '{{root}}'
  