# so to not be included in devenvs that include this
{% set included_workdirs = ['project', ] %}
{% set dev_req =     not is_included %}
{% set run_req =         is_included %}
{% set wrapped_exe = not is_included %}

channels:
  - conda-forge
environment:
  # probably want to append PATH and PYTHONPATH in your env
  PATH:
    - '{{ os.path.join(root, "wbin") }}'
    - '{{root}}'
  PYTHONPATH:
    - '{{root}}'
  # don't define the following in envs that include this
  WORK_DIR: '{{  os.path.basename(root) }}'                       # [not is_included]
  WORKDIR:  '{{  os.path.basename(root) }}'                       # [not is_included]
  WORK_DIR_PATH: '{{root}}'                                       # [not is_included]
  WORKDIR_PATH:  '{{root}}'                                       # [not is_included]
  PROJECTROOT:  '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
  PROJECT_ROOT: '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
dependencies:
  - pyprojroot=0.2.0 # minimal package so /something/ gets installed into dependent env
  # otherwise conda will not list the created env :/
  # some of the below tools will be exposed via wrappers in wbin
  # ie, they will not be 'installed' in dependent envs (envs that include this)
  - python=3.7            # [not is_included]
  - gitpython=3.1.3       # [not is_included]
  - exec-wrappers=1.1.4   # [not is_included]
  - invoke=1.4.1          # [not is_included]
  - dvc=1.4.0             # [wrapped_exe]
  - git                   # [wrapped_exe]
  - deps=1.1.1            # [wrapped_exe]
  - pre-commit=2.6.0      # [wrapped_exe]
name: {{'estcp-' + os.path.basename(root)}}
