# copy/paste into your work dir
#                           add more work dirs if needed
{% set dev_req =     not is_included %}
{% set run_req =         is_included %}
{% set wrapped_exe = not is_included %}

#                almost need 'project' but 'notebooking' is optional
{% set included_workdirs = ['project', 'notebooking'] %}

dependencies:
  {% if 'notebooking' in included_dirs %}
  - ipykernel   # also can have irkernel
  {% endif %}
  #- sometestframework         # [dev_req]
  #- some analysis library     # [run_req]
environment:
  # probably want to append to PATH and PYTHONPATH in your env
  PATH:
    - '{{root}}'
  PYTHONPATH:
    - '{{root}}'
  #                              don't define the following in envs that include this
  WORK_DIR: '{{  os.path.basename(root) }}'                       # [not is_included]
  WORKDIR:  '{{  os.path.basename(root) }}'                       # [not is_included]
  WORK_DIR_PATH: '{{root}}'                                       # [not is_included]
  WORKDIR_PATH:  '{{root}}'                                       # [not is_included]
  PROJECTROOT:  '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
  PROJECT_ROOT: '{{ os.path.abspath(os.path.join(root, '..')) }}' # [not is_included]
includes:
{% for included in included_workdirs %}
  - '{{root}}/../{{included}}/environment.devenv.yml'
{% endfor %}
name: {{'estcp-' + os.path.basename(root)}}
