
{%set project_name=  os.path.basename(os.path.abspath(os.path.join(root, '..')))  %}
name: {{project_name}}-{{os.path.basename(root)}}

{% set keep_here =     not is_included %}  # https://github.com/ESSS/conda-devenv/issues/120
{% set dev_req =       keep_here %}
{% set wrapped_exe =   keep_here %}
{% set run_req =       True %}  # serves as just annotation


# 'internal' dependency mgt. for includes: section
{% set included_workdir_pths = [] %}
{% set all_workdir_pths = [] %}
{% macro append_workdir_name(workdir, to) -%}
  {% set wdpth = os.path.abspath(os.path.join(root, '..', workdir))   %}
  {%if os.path.exists(os.path.join(wdpth, 'environment.devenv.yml')) %}
    {{ to.append(wdpth) or "" }} #"" is just a hack to not output None)
  {% endif %}
{%- endmacro %}
{% for maybe_workdir in  os.scandir( os.path.abspath(os.path.join(root, '..')) )   %}
      {{append_workdir_name(os.path.basename(maybe_workdir), all_workdir_pths)}}
{% endfor %}



{% if included_workdir_pths %}
includes:
  {% for included in included_workdir_pths %}
  - {{(os.path.join(included, 'environment.devenv.yml'))}}
  {% endfor %}
{% endif %}


channels:
  - conda-forge
dependencies:
  - pyprojroot=0.2.0          # [keep_here]
  # some of the below tools will be exposed via wrappers in wbin
  # ie, they will not be 'installed' in dependent envs (envs that include this)
  # keep python fixed
  - python=3.8                # [keep_here]
  - pylint                    # [dev_req]
  # code mgt
  - gitpython=3.1             # [keep_here]
  - git                       # [wrapped_exe]
  - pre-commit=2.10           # [wrapped_exe]
  # env mgt.
  - deps=1.1.1                # [wrapped_exe]
  - exec-wrappers=1.1.4       # [keep_here]
  # automation
  - invoke=1.5.0              # [wrapped_exe]  # as 'project' exec

environment:
  GIT_PYTHON_REFRESH: quiet   # windows problem https://github.com/gitpython-developers/GitPython/issues/816
  PATH:
    #adds all wrapped executables to path. NOT RECOMMENDED. exception for 'project' env
    {% set path_allworkdirs=True %}
    {% if path_allworkdirs %}
    {% for workdir_pth in all_workdir_pths  %}
    {% if  keep_here and os.path.basename(root)!=os.path.basename(workdir_pth) %}
    - {{ os.path.join(workdir_pth, "wbin") }}                     # [keep_here]
    {% endif %}
    {% endfor %}
    {% endif %}
    # adds included workdir wrapped execs
    {% for workdir_pth in included_workdir_pths %}
    # ...but dont add self
    {% if os.path.basename(root)!=os.path.basename(workdir_pth) 
      and (workdir_pth not in all_workdir_pths if path_allworkdirs else True)
    %}
    - {{os.path.join(workdir_pth, "wbin")}}
    {% endif %}
    {% endfor %}
    # append self dirs *after*
    # self unwrapped bins before others
    - {{os.path.join(root, 'scripts', 'bin')}}                    # [keep_here]
    # probably want to append to PATH and PYTHONPATH in your env
    - {{root}}
  PYTHONPATH:
    - {{root}}
  # don't define the following in envs that include this
  # dooesnt make sense to have the following in envs that include this one
  WORK_DIR: '{{  os.path.basename(root) }}'                       # [keep_here]
  WORKDIR:  '{{  os.path.basename(root) }}'                       # [keep_here]
  WORK_DIR_PATH: '{{root}}'                                       # [keep_here]
  WORKDIR_PATH:  '{{root}}'                                       # [keep_here]
  PROJECTROOT:  '{{ os.path.abspath(os.path.join(root, '..')) }}' # [keep_here]
  PROJECT_ROOT: '{{ os.path.abspath(os.path.join(root, '..')) }}' # [keep_here]
  PROJECT_NAME: '{{project_name}}'                                # [keep_here]
  # ...plus, cant merge this key in a env that includes it
  MODE: local-dev  # vs. prod                                     # [keep_here]
