variation:
  models:
  - 7d076f9a92 # architecture/rooms and lighting fixtures
  - 0deebd69f8 # architecture/lighting device        
  - c08764c302 # architecture/hvac zone
  - 0656898fdf # electrical/panels
  - 943dd188c7 # electrical/electrical connection
  sparql_rules:
  - ./../../../rules/data/AC
  - ./../../../rules/mappings/common
  - ./../../../rules/mappings/AC
  inference: true
  validation: true