PREFIX meta: <http://meta>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 


CONSTRUCT { 
?o1 s223:hasPhysicalLocation ?o2. 
} 
WHERE { 
?o1 a s223:Luminaire.
<<?o1 spkl:category "Lighting Fixtures">> meta: <<?_ spkl:name "architecture/rooms and lighting fixtures">>.
?o1 spkl:roomId ?rl.
#?o2 a s223:PhysicalSpace.
<<?o2 spkl:category  "Rooms">> meta: <<?_ spkl:name "architecture/rooms and lighting fixtures">>.
?o2 spkl:elementId ?rl.



}