PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
PREFIX meta: <http://meta>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT { 
         
    _:w a  s223:ElectricWire.
    _:w  s223:hasMedium  s223:Medium-Electricity.
    _:w rdfs:label ?f.
    ?this1 s223:connectedThrough _:w.
    } 
WHERE { 
?this1 a s223:Luminaire.
<<?this1 spkl:category  "Lighting Fixtures">> meta: <<?rl spkl:name "architecture/rooms and lighting fixtures">>.
?this1 spkl:elementId ?eid.
    <<?this spkl:category  "Lighting Fixtures">> meta: <<?mi spkl:name "electrical/electrical connection">>.
    ?this spkl:elementId ?eid.
         ?this spkl:parameters/spkl:RBS_ELEC_CIRCUIT_PANEL_PARAM/spkl:value ?f.
}