PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 


CONSTRUCT { 
?this s223:cnx ?conn.
  ?conn  a s223:OutletConnectionPoint.
  ?conn s223:hasMedium s223:AC-120VLN-1Ph-60Hz. # can this be inferred? 
} 
WHERE { 
?this a s223:ElectricBreaker.
    ?this spkl:Connectors/rdf:rest*/rdf:first ?conn. # there are two for each. 
}