PREFIX s223: <http://data.ashrae.org/standard223#>


CONSTRUCT { 
    _:conn      s223:cnx   ?b.
    _:conn      a                   s223:ElectricWire.
    # why is this not inferred??
    _:conn  s223:hasMedium          s223:AC-120VLN-1Ph-60Hz.
    #_:conn  s223:connectsTo         ?l.
} 
WHERE { 
    
    ?b a s223:InletConnectionPoint.
    ?b s223:hasMedium s223:AC-120VLN-1Ph-60Hz.
}