PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
PREFIX meta: <http://meta>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT { 
    ?e      a  s223:ElectricWire.
    ?e  s223:hasMedium  s223:Medium-Electricity.
    } 
WHERE { 
    <<?this spkl:category  "Lighting Fixtures">> meta: <<?mi spkl:name "electrical/electrical connection">>.
         ?this spkl:parameters/spkl:RBS_ELEC_CIRCUIT_NUMBER/spkl:value ?e.
}