PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX meta: <http://meta>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX spkl: <http://speckle.systems/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
?cp s223:cnx ?this.
}
WHERE {
?cp a  s223:ElectricWire.
?cp rdfs:label ?n.
<<?thisconn spkl:category  "Lighting Fixtures">> meta: <<?mi spkl:name "electrical/electrical connection">>.
?thisconn spkl:parameters/spkl:RBS_ELEC_CIRCUIT_PANEL_PARAM/spkl:value ?n.
?thisconn spkl:elementId ?eid.
?thisconn spkl:Connectors/rdf:rest*/rdf:first ?this.
?this a s223:InletConnectionPoint.
?this s223:hasMedium s223:AC-120VLN-1Ph-60Hz.
?this s223:cnx ?l.
?l a s223:Luminaire.
<<?l spkl:category  "Lighting Fixtures">> meta: <<?mi spkl:name "architecture/rooms and lighting fixtures">>.
?l spkl:elementId ?eid. 
}
 
