PREFIX geom: <http://mapping/geo#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
PREFIX meta: <http://meta>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT { 
?o s223:cnx ?e.
?o s223:connectsThrough ?e.
} 
WHERE { 
?eb s223:cnx ?o.
?eb a s223:ElectricBreaker. 
?eb  spkl:parameters/spkl:RBS_ELEC_PANEL_NAME/spkl:value ?n.
?o  a s223:OutletConnectionPoint.
?o s223:hasMedium s223:AC-120VLN-1Ph-60Hz.
?e a  s223:ElectricWire.
?e s223:hasMedium  s223:Medium-Electricity.
?e rdfs:label ?n.
}