PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT { 
?this s223:cnx ?conn.
?this s223:hasConnectionPoint ?conn.
?conn s223:isConnectionPointOf ?this.
  ?conn  a s223:OutletConnectionPoint.
  ?conn rdfs:label "OutletConnectionPoint"^^xsd:string.
  ?conn s223:hasMedium s223:AC-120VLN-1Ph-60Hz. # can this be inferred? 
} 
WHERE { 
?this a s223:ElectricBreaker.
    ?this spkl:Connectors/rdf:rest*/rdf:first ?conn. # there are two for each. 
}
