PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meta: <http://meta>

CONSTRUCT {
?lum s223:cnx ?conn.
?conn  a s223:InletConnectionPoint.
?conn rdfs:label "InletConnectionPoint"^^xsd:string.
?conn s223:hasMedium s223:AC-120VLN-1Ph-60Hz. 
?conn s223:cnx _:luminairewire.
_:luminairewire a s223:ElectricWire.
_:luminairewire s223:hasMedium  s223:Medium-Electricity.
_:luminairewire rdfs:label "ElectricWire"^^xsd:string.
_:luminairewire s223:cnx _:junctionoutlet.
_:junctionoutlet a s223:OutletConnectionPoint.
_:junctionoutlet rdfs:label "OutletConnectionPoint"^^xsd:string.
_:junctionoutlet s223:hasMedium s223:AC-120VLN-1Ph-60Hz. 
?lum ?circuit _:junctionoutlet.
 _:junctionoutlet s223:cnx ?j.
}
WHERE 
   {
?lum a s223:Luminaire. 
<<?lum spkl:category  "Lighting Fixtures">> meta: <<?rl spkl:name "architecture/rooms and lighting fixtures">>.
?lum spkl:elementId ?eid.
?lumcircuit spkl:Connectors/rdf:rest*/rdf:first ?conn.
<<?lumcircuit spkl:category  "Lighting Fixtures">> meta: <<?mi spkl:name "electrical/electrical connection">>.
?lumcircuit spkl:elementId ?eid.
?lumcircuit spkl:parameters/spkl:RBS_ELEC_CIRCUIT_PANEL_PARAM ?circuit.
?lumcircuit spkl:parameters/spkl:RBS_ELEC_CIRCUIT_PANEL_PARAM/spkl:value ?circuitname.
?j a s223:Junction.
?e a s223:ElectricWire.
?e rdfs:label ?circuitname.
<<?elecbreaker spkl:category  "Electrical Equipment">> meta: <<?si spkl:name "electrical/panels">>. 
?elecbreaker spkl:parameters/spkl:RBS_ELEC_PANEL_NAME/spkl:value ?circuitname. 
?e s223:cnx ?i.
?i a s223:InletConnectionPoint.
?i s223:cnx ?j.
   
}    
