PREFIX s223: <http://data.ashrae.org/standard223#>

CONSTRUCT { 
?o1     s223:connectedThrough   _:conn.
#  no em-light connection equivalent like pipe and wire
_:conn  a                       s223:Connection.
_:conn  s223:hasMedium          s223:Light-Visible.
_:conn  s223:connectsTo         ?o2.
} 
WHERE { 
# or use rdfstar to refer to luminaire-space mapping output?
?o1 s223:connectedTo ?o2.
?o1 a s223:Luminaire.
?o2 a s223:DomainSpace.
#?o2 s223:hasDomain s223:EM-Visible.
}
