PREFIX s223: <http://data.ashrae.org/standard223#>


CONSTRUCT { 
    ?b      s223:connectedThrough   _:conn.
    ?b      a                       s223:ElectricWire.
    _:conn  s223:connectsTo         ?l.
} 
WHERE { 
    ?b s223:connectedTo ?l.
    ?b a s223:ElectricBreaker.
    ?l a s223:Luminaire.
}