PREFIX geom: <http://mapping/geo#>
PREFIX s223: <http://data.ashrae.org/standard223#>



CONSTRUCT { 
?o1 s223:connectedTo ?o2.
} 
WHERE { 

?o1 a s223:OccupancySensor.

?o2 a s223:DomainSpace.
?o2 s223:hasDomain s223:Light-Visible. # domain-lighting should work.

?o1 geom:fracInside [
    ?o2  ?f].
filter(?f > .9)  # ...maybe a part of it is inside the ceiling? 
}