PREFIX meta: <http://meta>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 


CONSTRUCT { 
?this a s223:PhysicalSpace.
  ?this rdfs:label ?name.
  ?this s223:hasValue ?v.
  #?v a s223:QuantifiableActuatableProperty.
   
} 
WHERE { 
<<?this spkl:category  "Rooms">> meta: <<?_ spkl:name "architecture/rooms and lighting fixtures">>. # TODO branchName could be used here
    ?this spkl:name ?name. 
    ?this spkl:parameters/spkl:ROOM_AREA/spkl:value ?v.
   
}
