PREFIX rec: <https://w3id.org/rec#> 
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
PREFIX meta: <http://meta>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>


PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX qudtqk: <http://qudt.org/vocab/quantitykind/>
PREFIX unit: <http://qudt.org/vocab/unit/>
CONSTRUCT { 
?this a s223:PhysicalSpace.
?this rdfs:label ?name.
?this s223:hasProperty ?p.
?p a s223:QuantifiableProperty.
?p qudt:hasQuantityKind qudtqk:Area.
?p s223:hasValue ?vd.
?p qudt:hasUnit unit:M2.
?p rdfs:label "QuantifiableProperty"^^xsd:string.

} 
WHERE { 
<<?this spkl:category  "Rooms">> meta: <<?_ spkl:name "architecture/rooms and lighting fixtures">>. # TODO branchName could be used here
  ?this spkl:parameters/spkl:ROOM_AREA ?p.
  ?p spkl:value ?v.
  BIND(xsd:decimal(?v) AS ?vd).
  
OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "office")).  
      BIND(rec:OfficeRoom as ?name) 
    }
OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "corridor" )).  
      BIND(rec:Hallway as ?name) 
    }
OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "conference")).  
      BIND(rec:ConferenceRoom as ?name) 
    }
OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "storage")).  
      BIND(rec:Storage as ?name) 
    }
OPTIONAL
    {
      ?this spkl:name ?lname.  
        filter(
            contains(lcase(?lname), "restroom")  
            || contains(lcase(?lname), "bathroom" )).  
      BIND(rec:Bathroom as ?name) 
    }  
OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "kitchen" )).  
      BIND(rec:CookingRoom as ?name) 
    } 
    OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "dining" )).  
      BIND(rec:DiningRoom as ?name) 
    }
     OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "lobby" )).  
      BIND(rec:Lobby as ?name) 
    } 
     OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "lounge" )).  
      BIND(rec:Lounge as ?name) 
    } 
     OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "mechanical" )).  
      BIND(rec:UtilitiesRoom as ?name) 
    } 
     OPTIONAL
    {
      ?this spkl:name ?lname.  
      filter(contains(lcase(?lname), "stair" )).  
      BIND(rec:Stairwell as ?name) 
    } 
}

        