PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 


CONSTRUCT { 
?z  s223:hasDomainSpace  ?ds.
} 
WHERE { 
?z a s223:Zone.
    # relationship:
    ?z rdfs:label ?zn.
    ?z a s223:Zone.
    ?ds spkl:category  "Spaces".
    ?ds spkl:zoneName ?zn.
    ##
    ?ds a s223:DomainSpace. 
}