PREFIX geom: <http://mapping/geo#>
PREFIX s223: <http://data.ashrae.org/standard223#>
PREFIX spkl: <http://speckle.systems/> 
PREFIX meta: <http://meta>

CONSTRUCT { 
?o1 s223:hasPhysicalLocation ?o2.
} 
WHERE { 
?o1 a s223:OccupantMotionSensor.
<<?o1 spkl:category "Lighting Devices">> meta: <<?_ spkl:name "architecture/lighting device">>.
?o1 spkl:roomId ?rl.
<<?o2 spkl:category  "Rooms">> meta: <<?mi spkl:name "architecture/rooms and lighting fixtures">>.
?o2 spkl:elementId ?rl.
#?o2 s223:hasDomain s223:Light-Visible. # domain-lighting should work.


}