stages:
# or just have it as a manual cmd?
# use foreach? param sweep discussion https://github.com/iterative/dvc/pull/8187

  # all:
  #   foreach:
  #     - defs
  #     - all
  #     - applicable
    #do:
  ontology: # need to process ontology a bit more than just collecting files
  # this step is here instead of in 'ontologies' b/c of recursion issues.
  #                                                   param coll name?
    cmd: python -m mapping.engine ontology -i False -d 'ontology' -o ontology.ttl
    wdir: .
    deps:
      #- ../../ontologies/223standard.hash
      - ../../ontologies/.ontoenv # 
    outs:
     - ontology.ttl
  

  map:
    cmd: python -m mapping.speckle --stream_id=${building} --inference=True --validation=True 
    wdir: .
    deps:
      - ../mappings
      - ontology.ttl
    outs:
      - db

  report:
    cmd: quarto render report.qmd
    wdir: report
    deps:
      - ../db
      - report.qmd
      # - some other content
    outs:
      - report.html
      - report_files

  distribution:
    cmd: python distribution.py extract_triples db mapped shacl_inferred --replace_bdgprefix True -o mapped_plus_inferred.ttl
    wdir: .
    deps:
      - db
    outs:
      - mapped_plus_inferred.ttl
# test here? to actually error out if check?

# upload
#cmd: python -m graphdb.tasks upload_graph out.ttl --delete=True  --name ${building}