# "current"
run:
  #building: Pritoni. # use dvc exp run --set-param +run.building
  variation: default
  db: db # not part of 'variation'. fixed by default but putting here to be explicit
  max_cycles: 10  # ditto

# centralizing variations (ideal)
  building: Pritoni
variations:
# explict arguments
- name: default
  branches:
  - architecture/rooms and lighting fixtures
  - architecture/hvac zone
  - electrical/panels
  - electrical/electrical connection
  sparql_rules:
  - ../rules
  inference: true
  validation: true
distribution:
- name: Pritoni
  number: 1
- name: proto-medoffice
  number: 2
- name: lbnl-bldg59
  number: 3
- name: nrel-rail
  number: 4
- name: neea-medoffice
  number: 5
- name: Error
  number: 999
